# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=60)),
                ('version', models.CharField(max_length=60)),
                ('icon_url', models.CharField(blank=True, max_length=256)),
                ('settings_url', models.CharField(blank=True, max_length=256)),
                ('data_url', models.CharField(max_length=256)),
                ('allow_duplicates', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_json', models.TextField()),
                ('version', models.CharField(max_length=60)),
                ('last_updated_timestamp', models.DateTimeField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.App')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('icon_url', models.CharField(blank=True, max_length=256)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Calendar')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='framework.AppSettings')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='framework.CalendarUser'),
        ),
    ]
