# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 02:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20160313_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('green', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('blue', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.AddField(
            model_name='appsettings',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.Color'),
        ),
    ]
