# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_credentialsmodel_flowmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='framework.CalendarUser'),
            preserve_default=False,
        ),
    ]
