# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0006_calendaruser_isoauthed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='isOAuthed',
            field=models.IntegerField(default=-1),
        ),
    ]
