# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0008_auto_20160408_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='isOAuthed',
            field=models.BooleanField(default=False),
        ),
    ]
