# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0010_calendaruser_isdev'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='framework.CalendarUser'),
            preserve_default=False,
        ),
    ]
