# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0011_app_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='app',
            name='settings_url',
            field=models.CharField(max_length=256),
        ),
    ]
